[build]
  base    = "docusaurus/website"
  publish = "docusaurus/website/build"
  command = "yarn build"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]
